<?php
/**
 * Set additional NFT Memberships plugin constants.
 *
 * @package NFT_Memberships
 * @since 0.0.1
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

// Plugin Folder Path
if (!defined('NFT_MEMBERSHIPS_PLUGIN_DIR')) {
    define('NFT_MEMBERSHIPS_PLUGIN_DIR', plugin_dir_path(NFT_MEMBERSHIPS_PLUGIN_FILE));
} // end if;

// Plugin Folder URL
if (!defined('NFT_MEMBERSHIPS_PLUGIN_URL')) {
    define('NFT_MEMBERSHIPS_PLUGIN_URL', plugin_dir_url(NFT_MEMBERSHIPS_PLUGIN_FILE));
} // end if;

// Plugin Root File
if (!defined('NFT_MEMBERSHIPS_PLUGIN_BASENAME')) {
    define('NFT_MEMBERSHIPS_PLUGIN_BASENAME', plugin_basename(NFT_MEMBERSHIPS_PLUGIN_FILE));
} // end if;

//Plugin Name
if (!defined('NFT_MEMBERSHIPS_PLUGIN_NAME')) {
	define('NFT_MEMBERSHIPS_PLUGIN_NAME', 'NFT MEMBERSHIPS');
} // end if;

/**
 * Updater Constants
 *
 * For further details please visit http://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins
 *
 */
//Updater Url
if(!defined('NFT_MEMBERSHIPS_UPDATER_URL')){
	define('NFT_MEMBERSHIPS_UPDATER_URL', 'https://orbis86.com');
}

//Product ID in above url
if(!defined('NFT_MEMBERSHIPS_UPDATER_PRODUCT_ID')){
	define('NFT_MEMBERSHIPS_UPDATER_PRODUCT_ID', '4972');
}

/**
 * ACF Fields and Groups
 */
/*
 * Assign Owner Fields
 */
if( ! defined( 'NFT_MEMBERSHIPS_DOMAIN_DETAILS_GROUP_FIELD' ) ) {
	define('NFT_MEMBERSHIPS_DOMAIN_DETAILS_GROUP_FIELD', 'field_6152d656279cd');
}

if( ! defined( 'NFT_MEMBERSHIPS_ASSIGN_OWNER_FIELD' ) ){
	define( 'NFT_MEMBERSHIPS_ASSIGN_OWNER_FIELD', 'field_6152d6562bd4a' );
}

if( ! defined( 'NFT_MEMBERSHIPS_UPDATE_OWNER_FIELD' ) ){
	define( 'NFT_MEMBERSHIPS_UPDATE_OWNER_FIELD', 'field_6152d65624adf' );
}

/*
 * General Settings Fields
 */
if( ! defined('NFT_MEMBERSHIPS_GENERAL_SETTINGS_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_GENERAL_SETTINGS_GROUP', 'group_6310d5bd267c8');
}

if( ! defined('NFT_MEMBERSHIPS_GENERAL_SETTINGS_API_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_GENERAL_SETTINGS_API_FIELD', 'field_6310d5c632f81');
}

if( ! defined('NFT_MEMBERSHIPS_GENERAL_SETTINGS_MEMBERSHIP_PLUGIN_INTEGRATION_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_GENERAL_SETTINGS_MEMBERSHIP_PLUGIN_INTEGRATION_FIELD', 'field_6311960e367d4');
}

/*
 * Content Settings Fields
 */
if( ! defined('NFT_MEMBERSHIPS_CONTENT_SETTINGS_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SETTINGS_GROUP', 'group_63fc5922c938e');
}

// Overview Field Group
if( ! defined('NFT_MEMBERSHIPS_CONTENT_OVERVIEW_TAB_SETTINGS_FIELD_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_OVERVIEW_TAB_SETTINGS_FIELD_GROUP', 'field_641193d3483de');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_OVERVIEW_TAB_SETTINGS_NAME_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_OVERVIEW_TAB_SETTINGS_NAME_SUBFIELD', 'field_64119401483df');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_OVERVIEW_TAB_SETTINGS_CONTENT_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_OVERVIEW_TAB_SETTINGS_CONTENT_SUBFIELD', 'field_6411940f483e0');
}


// Subscriptions Field Group
if( ! defined('NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_FIELD_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_FIELD_GROUP', 'field_641193d34885m');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_NAME_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_NAME_SUBFIELD', 'field_6411940148n5n');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_CONTENT_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_CONTENT_SUBFIELD', 'field_6411940f4839g');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_ORDER_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SUBSCRIPTIONS_TAB_SETTINGS_ORDER_SUBFIELD', 'field_64119ef94d2f9');
}

// Wallet Field Group
if( ! defined('NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_FIELD_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_FIELD_GROUP', 'field_641193d34nd58');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_NAME_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_NAME_SUBFIELD', 'field_641194014ma38n');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_CONTENT_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_CONTENT_SUBFIELD', 'field_6411940falk3');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_ORDER_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_WALLET_TAB_SETTINGS_ORDER_SUBFIELD', 'field_64119ef9421qw');
}

// Services Field Group
if( ! defined('NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_FIELD_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_FIELD_GROUP', 'field_641193d34type');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_NAME_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_NAME_SUBFIELD', 'field_641194014askl');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_CONTENT_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_CONTENT_SUBFIELD', 'field_6411940fnrpd');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_ORDER_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_ORDER_SUBFIELD', 'field_64119ef9xcgh');
}

if( ! defined('NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_ALLOWED_MEMBERSHIPS_SUBFIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_CONTENT_SERVICES_TAB_SETTINGS_ALLOWED_MEMBERSHIPS_SUBFIELD', 'field_64119efqwmdh');
}


/*
 * Membership Settings Fields
 */
if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_GROUP', 'group_62f8c1dfc9n90');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_REPEATER_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_REPEATER_FIELD', 'field_630e005894926');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_NAME_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_NAME_FIELD', 'field_63017de010536');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_COLLECTION_NAME_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_COLLECTION_NAME_FIELD', 'field_630e010517d05');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_PRIVATE_NOTE_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_PRIVATE_NOTE_FIELD', 'field_6310d5c6b6m89');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_DESCRIPTION_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_DESCRIPTION_FIELD', 'field_63f71e2321efd');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_NETWORK_TYPE_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_NETWORK_TYPE_FIELD', 'field_63dcc1d81e6e4');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_BLOCKCHAIN_TYPE_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_BLOCKCHAIN_TYPE_FIELD', 'field_630e006694927');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_HEDERA_TYPE_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_HEDERA_TYPE_FIELD', 'field_630e006659b47');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_CONTRACT_ADDRESS_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_CONTRACT_ADDRESS_FIELD', 'field_630e04e763abc');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_CHECK_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_CHECK_FIELD', 'field_630e0279109d1');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_NFT_CHECK_COMPARISON_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_NFT_CHECK_COMPARISON_FIELD', 'field_6311b3bafb118');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_COLLECTION_NFTS_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_COLLECTION_NFTS_FIELD', 'field_630e018f1fa3a');
}

if( ! defined('NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_MEMBERSHIPS_SETTINGS_MEMBERSHIP_FIELD', 'field_630e054e124b4');
}

if( ! defined('NFT_MEMBERSHIPS_USER_MEMBERSHIPS_SETTINGS_GROUP' ) )
{
	define( 'NFT_MEMBERSHIPS_USER_MEMBERSHIPS_SETTINGS_GROUP', 'group_63e1e67b61bb3');
}

if( ! defined('NFT_MEMBERSHIPS_USER_MEMBERSHIPS_MEMBERSHIPS_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_USER_MEMBERSHIPS_MEMBERSHIPS_FIELD', 'field_63e1e67d3517a');
}

if( ! defined('NFT_MEMBERSHIPS_USER_MEMBERSHIPS_WALLET_ADDRESS_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_USER_MEMBERSHIPS_WALLET_ADDRESS_FIELD', 'field_6411390e83j76');
}

if( ! defined('NFT_MEMBERSHIPS_USER_MEMBERSHIPS_ACCOUNT_ID_FIELD' ) )
{
	define( 'NFT_MEMBERSHIPS_USER_MEMBERSHIPS_ACCOUNT_ID_FIELD', 'field_63e1e67d35c5m');
}


